# Compares  mean stem and crown ages for dating analyses implementing different calibration strategies. 
# - SA = Constrained Calibration (CC)
# - SB = Relaxed Calibration (RC)
# - SD = Unconstrained Calibration (UC)
# Uses additional files

rich <- read.table("SPP.RICHNESS.csv",heade=T,sep=",") # file in data folder
resB <- read.table("RES_SBphylo_v2/2.Ages_complete.csv",sep=",",header=T) # generated by the preceding scripts
rich_ord<-rich[which(rich$Family==""),]; dim(rich_ord)
resB$Order_richness<-rich_ord[match(resB$Order,rich_ord$Order),"Spp_richness"]
rich_fams<-rich[which(rich$Subfamily==""),]; dim(rich_fams)
rich_fams<-rich_fams[which(rich_fams$Family!=""),]; dim(rich_fams)
resB$Family_richness<-rich_fams[match(resB$Family,rich_fams$Family),"Spp_richness"]
rich_subfams<-rich[which(rich$Subfamily!=""),]; dim(rich_subfams)
resB$Subfamily_richness<-rich_subfams[match(resB$Subfamily,rich_subfams$Subfamily),"Spp_richness"]
non<-which(rownames(resB) %in% c( "Aphloiaceae","Brunelliaceae","Cynomoriaceae", 
                                  "Daphniphyllaceae", "Mayacaceae",
                                  "Mitrastemonaceae","Oncothecaceae"))
resB[non,"CG_age_Acal"]<-NA; resB[non,"CG_minHPD"]<-NA; resB[non,"CG_maxHPD"]<-NA
resB$Total_Richness <- rep(NA,dim(resB)[1])
for (i in 1:dim(resB)[1]){ 
  if(!is.na(resB$Subfamily_richness[i])){resB$Total_Richness[i] <- resB$Subfamily_richness[i];next}
  if(!is.na(resB$Family_richness[i])){resB$Total_Richness[i] <- resB$Family_richness[i];next}
  resB$Total_Richness[i] <- resB$Order_richness[i]}
out.group<-which(resB$Order%in%c("Pinales","Gnetales","Ginkgoales","Cycadales"))
resB<-resB[-out.group,]
orders<-1:64
fams<-65:500
subfams<-501:dim(resB)[1]
resB_fams<-resB[fams,]

resB<-read.table("RES_SAphylo_v2/2.Ages_complete.csv",sep=",",header=T) # generated by the preceding scripts
rich_ord<-rich[which(rich$Family==""),]; dim(rich_ord)
resB$Order_richness<-rich_ord[match(resB$Order,rich_ord$Order),"Spp_richness"]
rich_fams<-rich[which(rich$Subfamily==""),]; dim(rich_fams)
rich_fams<-rich_fams[which(rich_fams$Family!=""),]; dim(rich_fams)
resB$Family_richness<-rich_fams[match(resB$Family,rich_fams$Family),"Spp_richness"]
rich_subfams<-rich[which(rich$Subfamily!=""),]; dim(rich_subfams)
resB$Subfamily_richness<-rich_subfams[match(resB$Subfamily,rich_subfams$Subfamily),"Spp_richness"]
non<-which(rownames(resB) %in% c( "Aphloiaceae","Brunelliaceae","Cynomoriaceae", 
                                  "Daphniphyllaceae", "Mayacaceae",
                                  "Mitrastemonaceae","Oncothecaceae"))
resB[non,"CG_age_Acal"]<-NA; resB[non,"CG_minHPD"]<-NA; resB[non,"CG_maxHPD"]<-NA
resB$Total_Richness <- rep(NA,dim(resB)[1])
for (i in 1:dim(resB)[1]){ 
  if(!is.na(resB$Subfamily_richness[i])){resB$Total_Richness[i] <- resB$Subfamily_richness[i];next}
  if(!is.na(resB$Family_richness[i])){resB$Total_Richness[i] <- resB$Family_richness[i];next}
  resB$Total_Richness[i] <- resB$Order_richness[i]}
out.group<-which(resB$Order%in%c("Pinales","Gnetales","Ginkgoales","Cycadales"))
resB<-resB[-out.group,]
orders<-1:64
fams<-65:500
resB[490:501,]
subfams<-501:dim(resB)[1]
resA_fams<-resB[fams,]

resB<-read.table("RES_SDphylo_v2/2.Ages_complete.csv",sep=",",header=T) # generated by the preceding scripts
rich_ord<-rich[which(rich$Family==""),]; dim(rich_ord)
resB$Order_richness<-rich_ord[match(resB$Order,rich_ord$Order),"Spp_richness"]
rich_fams<-rich[which(rich$Subfamily==""),]; dim(rich_fams)
rich_fams<-rich_fams[which(rich_fams$Family!=""),]; dim(rich_fams)
resB$Family_richness<-rich_fams[match(resB$Family,rich_fams$Family),"Spp_richness"]
rich_subfams<-rich[which(rich$Subfamily!=""),]; dim(rich_subfams)
resB$Subfamily_richness<-rich_subfams[match(resB$Subfamily,rich_subfams$Subfamily),"Spp_richness"]
non<-which(rownames(resB) %in% c( "Aphloiaceae","Brunelliaceae","Cynomoriaceae", 
                                  "Daphniphyllaceae", "Mayacaceae",
                                  "Mitrastemonaceae","Oncothecaceae"))
resB[non,"CG_age_Acal"]<-NA
resB[non,"CG_minHPD"]<-NA
resB[non,"CG_maxHPD"]<-NA
resB$Total_Richness <- rep(NA,dim(resB)[1])
for (i in 1:dim(resB)[1]){ 
  if(!is.na(resB$Subfamily_richness[i])){resB$Total_Richness[i] <- resB$Subfamily_richness[i];next}
  if(!is.na(resB$Family_richness[i])){resB$Total_Richness[i] <- resB$Family_richness[i];next}
  resB$Total_Richness[i] <- resB$Order_richness[i]}
out.group<-which(resB$Order%in%c("Pinales","Gnetales","Ginkgoales","Cycadales"))
resB<-resB[-out.group,]
orders<-1:64
fams<-65:500
resB[490:501,]
subfams<-501:dim(resB)[1]
resD_fams<-resB[fams,]

pdf("1.Comparison_strategies_conservative.pdf")
par(mfrow=c(2,2))
plot(resB_fams$SG_age_Acal,resA_fams$SG_age_Acal,xlim=c(0,250),ylim=c(0,250),type="n",
     xlab="Relaxed Calibration (RC)",ylab="Constrained Calibration (CC)"); abline(a=0,b=1)
for (i in 1:length(resB_fams$SG_age_Acal)) segments(y0=resA_fams$SG_minHPD[i],y1=resA_fams$SG_maxHPD[i],
                                                    x0=resB_fams$SG_age_Acal[i],x1=resB_fams$SG_age_Acal[i],lwd = 0.5,col="grey60")
for (i in 1:length(resB_fams$SG_age_Acal)) segments(x0=resB_fams$SG_minHPD[i],x1=resB_fams$SG_maxHPD[i],
                                                    y0=resA_fams$SG_age_Acal[i],y1=resA_fams$SG_age_Acal[i],lwd = 0.5,col="grey60")
points(resB_fams$SG_age_Acal,resA_fams$SG_age_Acal,pch=19,cex=0.4,col=rgb(0,0,0,0.5))

plot(resB_fams$SG_age_Acal,resD_fams$SG_age_Acal,xlim=c(0,250),ylim=c(0,250),type="n",
     xlab="Relaxed Calibration (RC)",ylab="Unconstrained Calibration (UC)"); abline(a=0,b=1)
for (i in 1:length(resB_fams$SG_age_Acal)) segments(y0=resD_fams$SG_minHPD[i],y1=resD_fams$SG_maxHPD[i],
                                                    x0=resB_fams$SG_age_Acal[i],x1=resB_fams$SG_age_Acal[i],lwd = 0.5,col="grey60")
for (i in 1:length(resB_fams$SG_age_Acal)) segments(x0=resB_fams$SG_minHPD[i],x1=resB_fams$SG_maxHPD[i],
                                                    y0=resD_fams$SG_age_Acal[i],y1=resD_fams$SG_age_Acal[i],lwd = 0.5,col="grey60")
points(resB_fams$SG_age_Acal,resD_fams$SG_age_Acal,pch=19,cex=0.4,col=rgb(0,0,0,0.5))

plot(resA_fams$SG_age_Acal,resD_fams$SG_age_Acal,xlim=c(0,250),ylim=c(0,250),type="n",
     xlab="Constrained Calibration (CC)",ylab="Unconstrained Calibration (UC)"); abline(a=0,b=1)
for (i in 1:length(resA_fams$SG_age_Acal)) segments(y0=resD_fams$SG_minHPD[i],y1=resD_fams$SG_maxHPD[i],
                                                    x0=resA_fams$SG_age_Acal[i],x1=resA_fams$SG_age_Acal[i],lwd = 0.5,col="grey60")
for (i in 1:length(resA_fams$SG_age_Acal)) segments(x0=resA_fams$SG_minHPD[i],x1=resA_fams$SG_maxHPD[i],
                                                    y0=resD_fams$SG_age_Acal[i],y1=resD_fams$SG_age_Acal[i],lwd = 0.5,col="grey60")
points(resA_fams$SG_age_Acal,resD_fams$SG_age_Acal,pch=19,cex=0.4,col=rgb(0,0,0,0.5))

calstrats <- c(rep("RC",436),rep("CC",436),rep("UC",436))
stemas <- c(resB_fams$SG_maxHPD-resB_fams$SG_minHPD,
            resA_fams$SG_maxHPD-resA_fams$SG_minHPD,
            resD_fams$SG_maxHPD-resD_fams$SG_minHPD)
boxplot(stemas~calstrats,ylab="Million years",col=c("grey30","grey60","grey90"),ylim=c(0,140))

par(mfrow=c(2,2))
plot(resB_fams$CG_age_Acal,resA_fams$CG_age_Acal,xlim=c(0,250),ylim=c(0,250),type="n",
     xlab="Relaxed Calibration (RC)",ylab="Constrained Calibration (CC)"); abline(a=0,b=1)
for (i in 1:length(resB_fams$CG_age_Acal)) segments(y0=resA_fams$CG_minHPD[i],y1=resA_fams$CG_maxHPD[i],
                                                    x0=resB_fams$CG_age_Acal[i],x1=resB_fams$CG_age_Acal[i],lwd = 0.5,col="grey60")
for (i in 1:length(resB_fams$CG_age_Acal)) segments(x0=resB_fams$CG_minHPD[i],x1=resB_fams$CG_maxHPD[i],
                                                    y0=resA_fams$CG_age_Acal[i],y1=resA_fams$CG_age_Acal[i],lwd = 0.5,col="grey60")
points(resB_fams$CG_age_Acal,resA_fams$CG_age_Acal,pch=19,cex=0.4,col=rgb(0,0,0,0.5))

plot(resB_fams$CG_age_Acal,resD_fams$CG_age_Acal,xlim=c(0,250),ylim=c(0,250),type="n",
     xlab="Relaxed Calibration (RC)",ylab="Unconstrained Calibration (UC)"); abline(a=0,b=1)
for (i in 1:length(resB_fams$CG_age_Acal)) segments(y0=resD_fams$CG_minHPD[i],y1=resD_fams$CG_maxHPD[i],
                                                    x0=resB_fams$CG_age_Acal[i],x1=resB_fams$CG_age_Acal[i],lwd = 0.5,col="grey60")
for (i in 1:length(resB_fams$CG_age_Acal)) segments(x0=resB_fams$CG_minHPD[i],x1=resB_fams$CG_maxHPD[i],
                                                    y0=resD_fams$CG_age_Acal[i],y1=resD_fams$CG_age_Acal[i],lwd = 0.5,col="grey60")
points(resB_fams$CG_age_Acal,resD_fams$CG_age_Acal,pch=19,cex=0.4,col=rgb(0,0,0,0.5))

plot(resA_fams$CG_age_Acal,resD_fams$CG_age_Acal,xlim=c(0,250),ylim=c(0,250),type="n",
     xlab="Constrained Calibration (CC)",ylab="Unconstrained Calibration (UC)"); abline(a=0,b=1)
for (i in 1:length(resA_fams$CG_age_Acal)) segments(y0=resD_fams$CG_minHPD[i],y1=resD_fams$CG_maxHPD[i],
                                                    x0=resA_fams$CG_age_Acal[i],x1=resA_fams$CG_age_Acal[i],lwd = 0.5,col="grey60")
for (i in 1:length(resA_fams$CG_age_Acal)) segments(x0=resA_fams$CG_minHPD[i],x1=resA_fams$CG_maxHPD[i],
                                                    y0=resD_fams$CG_age_Acal[i],y1=resD_fams$CG_age_Acal[i],lwd = 0.5,col="grey60")
points(resA_fams$CG_age_Acal,resD_fams$CG_age_Acal,pch=19,cex=0.4,col=rgb(0,0,0,0.5))

calstrats <- c(rep("RC",436),rep("CC",436),rep("UC",436))
crownas <- c(resB_fams$CG_maxHPD-resB_fams$CG_minHPD,
            resA_fams$CG_maxHPD-resA_fams$CG_minHPD,
            resD_fams$CG_maxHPD-resD_fams$CG_minHPD)
boxplot(crownas~calstrats,ylab="Million years",col=c("grey30","grey60","grey90"),ylim=c(0,140))
dev.off()
